-- Комментарии к событию
CREATE SCHEMA IF NOT EXISTS comments;
CREATE TABLE IF NOT EXISTS comments.comments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    created TIMESTAMP NOT NULL
);