-- Таблица запросов на участие
CREATE TABLE IF NOT EXISTS requests.requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    requester_id INT NOT NULL,
    created TIMESTAMP NOT NULL
);