grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-consumer-group


kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

