spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: comments-service_route
          uri: lb://comments
          predicates:
            - Path=/admin/comments/**,/users/*/comment/**,/comment/**
        - id: requests-service_route
          uri: lb://requests
          predicates:
          - Path=/users/*/events/*/requests/**,/users/*/requests/**
        - id: users_service_route
          uri: lb://user-service
          predicates:
            - Path=/internal/users/**,/admin/users/**
        - id: events_core_route
          uri: lb://events
          predicates:
            - Path=/admin/events/**,/users/*/events/**,/events/**,/internal/events/**
        - id: events_category_route
          uri: lb://events
          predicates:
            - Path=/admin/categories/**,/categories/**
        - id: event_compilation_route
          uri: lb://events
          predicates:
              - Path=/admin/compilations/**,/compilations/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

