CREATE SCHEMA IF NOT EXISTS events;
-- Таблица категорий
CREATE TABLE IF NOT EXISTS events.categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events.events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category_id INT NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description TEXT,
    event_date TIMESTAMP NOT NULL,
    initiator_id INT NOT NULL,
    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT,
    published_on TIMESTAMP,
    confirmed_requests INT,
    request_moderation BOOLEAN,
    state VARCHAR(32),
    title VARCHAR(255) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);


-- Подборки событий
CREATE TABLE IF NOT EXISTS events.compilation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(255) NOT NULL
);

-- Связь многие ко многим
CREATE TABLE IF NOT EXISTS events.compilation_events (
    compilation_id INT NOT NULL,
    event_id INT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilation(id),
    FOREIGN KEY (event_id) REFERENCES events(id)
    );

